### ISSUE TITLE
mathematics-roadmap.jpg link broken

### ISSUE THREAD

**Issue by shanmuganathan-m** [TalalAlrawajfeh/mathematics-roadmap#3]
Unable to view open mathematics-roadmap.jpg.

The following link is broken.

https://raw.githubusercontent.com/TalalAlrawajfeh/mathematics-roadmap/master/mathematics-roadmap.jpg 

Kindly fix this issue.

**Comment by TalalAlrawajfeh** [comment]
I checked the link several times and it works fine.
