### ISSUE TITLE
Just want to deep dive into recrified flow

### ISSUE THREAD

**Issue by Oguzhanercan** [TalalAlrawajfeh/mathematics-roadmap#6]
I just want to deep dive into rectified flow (stable diffusion 3). Then see that I cannot understand dif eq. Then I see that I need to go back linear algebra. I belive that I will end up with 2+2 is equal to 4 (is that correct?).

Thanks for roadmap. Time to multiply some matrix.

**Comment by TalalAlrawajfeh** [comment]
Sorry for the late reply. I'm no expert in this, but it seems you will need to have some knowledge about stochastic differential equations first to understand rectified flow, and for that you would need to have a strong background in Probability Theory and Differential Equations which are included in the roadmap. Good luck!
