### ISSUE TITLE
Typo in a name

### ISSUE THREAD

**Issue by Julien-Glorian** [TalalAlrawajfeh/mathematics-roadmap#7]
Hello,
thanks a lot for your work, I really want to work on lot of subject that you have mentionned.
In the research of the documents, I found a little typo in a name, you wrote that the book Propositional and Predicate Calculus (in Introduction to Mathematical Loggic and Model Theory) was written by Derek Godrei but it's Derek Goldrei. This isn't really serious, but I want to show my respect to these people that I admire.

With best wishes,
Julien Glorian

PS : I am french and I'm not certain that my English is perfect.

**Comment by TalalAlrawajfeh** [comment]
Thank you for your support! The typo has now been fixed.
